spring:
  data:
    cassandra:
      contact-points: ${myapp.constants.cassandraUrl} 
      port: 9042
      local-datacenter: datacenter1
      keyspace-name: rideandgo
      schema-action: create-if-not-exists
  profiles:
    active: dev

myapp:
  constants:
    appName: "RideAndGo"
    cassandraUrl: "172.17.0.2"  

    
