spring:
  data:
    cassandra:
      contact-points: 0.0.0.0
      port: 9042
      local-datacenter: datacenter1
      keyspace-name: rideandgo
      schema-action: create-if-not-exists
  profiles:
    active: dev
